require:
 - rubocop-rails
 - rubocop-performance
 - rubocop-rspec

Style/NumericLiterals:
  Enabled: false

Layout/LineLength:
  Max: 160
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: 'no_space'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/support/*.rb'

Rails/SkipsModelValidations:
  Whitelist:
  - update_all
  - touch

Metrics/MethodLength:
  Description: 'Avoid methods longer than 12 lines of code.'
  Max: 12

Style/RegexpLiteral:
  EnforcedStyle: slashes

# disable 'Missing top-level class documentation' warning
Style/Documentation:
  Enabled: false

# new linters - opt in
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true