require:
 - rubocop-rails
 - rubocop-performance
 - rubocop-rspec

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 160
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: 'no_space'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 10
