language: ruby
cache: bundler
sudo: false

before_script: &before_script
  - psql -c 'create database travis_ci_test;' -U postgres
  - rename 's/\.yml.hudson$/\.yml/' config/*.yml.hudson
  - RACK_ENV=test bundle exec rake db:create db:migrate

jruby_before_script: &jruby_before_script
  - bundle exec jbundle install
  - psql -c 'create database travis_ci_test;' -U postgres
  - rename 's/\.yml.hudson$/\.yml/' config/*.yml.hudson
  - RACK_ENV=test bundle exec rake db:create db:migrate

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.0.0.0.pre1
  include:
    - rvm: jruby-1.7.18
      env: JRUBY_OPTS=--2.0
      jdk: openjdk7
      before_script: *jruby_before_script
    - rvm: 2.2.0
    - rvm: jruby-9.0.0.0.pre1
      jdk: openjdk7
      before_script: *jruby_before_script
    - rvm: jruby-head
      jdk: openjdk7
      before_script: *jruby_before_script
    - rvm: ruby-head
      
services:
  - postgresql

addons:
  postgresql: "9.3"

script: RACK_ENV=test bundle exec rake spec
