language: ruby

cache: bundler

jdk:
  - openjdk7

rvm:
  - 2.1.2
  - jruby-1.7.16
  - jruby-head

services:
  - postgresql

env: JRUBY_OPTS=--2.0

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rename 's/\.yml.hudson$/\.yml/' config/*.yml.hudson
  - RACK_ENV=test bundle exec rake db:create db:migrate

script: RACK_ENV=test bundle exec rake spec
