language: ruby
cache: bundler
sudo: false
bundler_args: --without development production
addons:
  postgresql: "9.5"

before_install:
  - mkdir -p tmp
  - find spec -maxdepth 1 -type d | grep spec/ > tmp/curr_spec_dirs.txt
  - if grep -Fxvc -f spec/known_dirs.txt tmp/curr_spec_dirs.txt; then echo 'Detected unkown Spec directories, check the spec/known_dirs.txt!'; exit 1; fi
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

before_script: &before_script
  - psql -c 'create database travis_ci_test;' -U postgres
  - scripts/no_focus.sh
  - bundle exec rake configure:local
  - echo Running script - bundle exec rspec $SPECS

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.6
  include:
    - rvm: 2.5
      env:
        - DATABASE_URL=postgresql://localhost/travis_ci_test?user=postgres
        - SPECS=spec/controllers/api/v1/[a-m]*.rb
    - rvm: 2.5
      env:
        - DATABASE_URL=postgresql://localhost/travis_ci_test?user=postgres
        - SPECS=spec/controllers/api/v1/[n-s]*.rb
    - rvm: 2.5
      env:
        - DATABASE_URL=postgresql://localhost/travis_ci_test?user=postgres
        - SPECS=spec/controllers/api/v1/[t-z]*.rb
    - rvm: 2.5
      env:
        - DATABASE_URL=postgresql://localhost/travis_ci_test?user=postgres
        - SPECS="spec/controllers/**.rb spec/controllers/api/*.rb spec/models spec/operations spec/counters spec/routes"
    - rvm: 2.5
      env:
        - DATABASE_URL=postgresql://localhost/travis_ci_test?user=postgres
        - SPECS="spec/lib spec/workers spec/serializers spec/services spec/requests spec/middleware spec/mailers spec/policies"
    - rvm: 2.6

script: "bundle exec rspec $SPECS"
