FROM ruby:2.5-slim-buster

WORKDIR /rails_app

RUN apt-get update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y \
      build-essential \
      # git is required for installing gems from git repos
      git \
      libpq-dev \
      # debian buster has v11 by default
      postgresql-client-11 \
      tmpreaper

ADD ./Gemfile /rails_app/
ADD ./Gemfile.lock /rails_app/

RUN bundle config --global jobs `cat /proc/cpuinfo | grep processor | wc -l | xargs -I % expr % - 1`
RUN bundle install

ADD ./ /rails_app

RUN (cd /rails_app && mkdir -p tmp/pids && rm -f tmp/pids/*.pid)

CMD ["/rails_app/scripts/docker/start.sh"]
