default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://panoptes:panoptes@localhost') %>
  pool: <%= ENV.fetch('PG_POOL_SIZE', 5) %>
  prepared_statements: <%= ENV.fetch('PG_PREPARED_STATEMENTS', false) %>
  variables:
    # default 5 minutes for the query exectution (sidekiq uses default, API will set the env param match load balancer)
    statement_timeout: <%= ENV.fetch('PG_STATEMENT_TIMEOUT', 300000) %>

development:
  <<: *default
  database: panoptes_development

development_standby:
  <<: *default
  database: panoptes_development

test:
  <<: *default
  database: panoptes_test

test_standby:
  <<: *default
  database: panoptes_test
