# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# sidekiq -C config.yml
---
:verbose: <%= !!ENV.fetch('SIDEKIQ_VERBOSE', false) %>
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 1).to_i %>
# Default graceperiod in K8s is 30s
# we can specify longer but will need to increase the terminationGracePeriod
# https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace
:timeout: <%= ENV.fetch('SIDEKIQ_TIMEOUT', 25).to_i %>
:queues:
  - really_high
  - high
  - data_high
  - data_medium
  - default
  - data_low
