# frozen_string_literal: true

# A SubjectGroup is a collection (cluster) of subjects that a user can classify
# They are generated by using the results of a user's subject selections
# and are stored in the database to enable the system to track what the user classifid on
#
# They have a special 'group_subject' that acts as the subject for use in the talk system
# as well as the existing API data model to enable the tracking of
#  lassifications, recents, seens data etc
#
# This class is not associated with the 'SubjectSet' class (a way to association subjects with a workflow)
class SubjectGroup < ActiveRecord::Base
  belongs_to :project
  has_many :subject_group_members, dependent: :destroy
  has_many :subjects, through: :subject_group_members
  # a 'group_subject' to record the grouped view of linked subject locations
  # for use in talk and to collect classifications, retirement information about the group
  belongs_to :group_subject, class_name: 'Subject'

  validates :project, presence: true
  validates :subject_group_members, presence: true
  validates :key, presence: true
  validates :group_subject, presence: true
end
