# frozen_string_literal: true

# A SubjectGroup is a collection (cluster) of subjects that a user can classify
# They are generated by using the results of a user's subject selections
# and are stored in the database to enable the system to track what the user classifid on
#
# They have a special 'group_subject' that acts as the subject for use in the talk system
# as well as the existing API data model to enable the tracking of
# classifications, recents, seens data etc
#
# This class is not associated with the 'SubjectSet' class (a way to association subjects with a workflow)
class SubjectGroup < ApplicationRecord
  belongs_to :project
  # a 'group_subject' to record the grouped view of linked subject locations
  # for use in talk and to collect classifications, retirement information about the group
  belongs_to :group_subject, class_name: 'Subject'

  validates :project, presence: true
  validates :key, presence: true
  validates :group_subject, presence: true

  def subject_ids_from_key
    key.split('-').map(&:to_i).reject(&:zero?)
  end

  def subjects
    ids = subject_ids_from_key
    return Subject.none if ids.empty?
    Subject.where(id: ids).order(Arel.sql("array_position(ARRAY[#{ids.join(',')}], id)"))
  end
end
