ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets', '~> 4.1'
gem 'middleman-syntax', '~> 3.0'
gem 'nokogiri', '~> 1.12'
gem 'redcarpet', '~> 3.5'
gem 'rouge', '~> 2.0'
