name: Deploy Staging Canary

on:
  workflow_dispatch:

jobs:
  deploy_staging_canary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create commit_id.txt
      run: echo '${{ github.sha }}-next' > commit_id.txt

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.rails-next
        push: true
        tags: ghcr.io/zooniverse/panoptes:${{ github.sha }}-next
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set the target AKS cluster
      uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_AKS }}'
        cluster-name: microservices
        resource-group: kubernetes

    - name: Modify & apply template
      run: |
        sed "s/__IMAGE_TAG__/${{ github.sha }}/g" ./kubernetes/deployment-staging-canary.tmpl \
          | kubectl apply -f -
